-- MySQL Script generated by MySQL Workbench
-- Mon 05 Nov 2018 12:14:07 AM -02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema carrinho_compras
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema carrinho_compras
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `carrinho_compras` ;
USE `carrinho_compras` ;

-- -----------------------------------------------------
-- Table `carrinho_compras`.`cupom_descontos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carrinho_compras`.`cupom_descontos` ;

CREATE TABLE IF NOT EXISTS `carrinho_compras`.`cupom_descontos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `localizador` VARCHAR(255) NULL DEFAULT NULL,
  `desconto` DECIMAL(6,2) NULL DEFAULT NULL,
  `modo_desconto` VARCHAR(10) NULL DEFAULT NULL,
  `limite` DECIMAL(6,2) NULL DEFAULT NULL,
  `modo_limite` ENUM('valor', 'qtd') NULL DEFAULT NULL,
  `dthr_validade` DATETIME NULL DEFAULT NULL,
  `ativo` ENUM('S', 'N') NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `carrinho_compras`.`password_resets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carrinho_compras`.`password_resets` ;

CREATE TABLE IF NOT EXISTS `carrinho_compras`.`password_resets` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `token` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `carrinho_compras`.`produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carrinho_compras`.`produtos` ;

CREATE TABLE IF NOT EXISTS `carrinho_compras`.`produtos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `valor` DECIMAL(6,2) NULL DEFAULT NULL,
  `imagem` VARCHAR(255) NULL DEFAULT NULL,
  `ativo` ENUM('S', 'N') NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `carrinho_compras`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carrinho_compras`.`users` ;

CREATE TABLE IF NOT EXISTS `carrinho_compras`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL COMMENT '\\n',
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `type` VARCHAR(45) NULL DEFAULT 'default',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `carrinho_compras`.`pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carrinho_compras`.`pedidos` ;

CREATE TABLE IF NOT EXISTS `carrinho_compras`.`pedidos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(10) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_pedidos_users_idx` ON `carrinho_compras`.`pedidos` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `carrinho_compras`.`pedido_produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carrinho_compras`.`pedido_produtos` ;

CREATE TABLE IF NOT EXISTS `carrinho_compras`.`pedido_produtos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(10) NULL DEFAULT NULL,
  `valor` DECIMAL(6,2) NULL DEFAULT NULL,
  `desconto` DECIMAL(6,2) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `produto_id` INT(11) NOT NULL,
  `pedido_id` INT(11) NOT NULL,
  `cupom_descontos_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_pedido_produtos_produtos1_idx` ON `carrinho_compras`.`pedido_produtos` (`produto_id` ASC);

CREATE INDEX `fk_pedido_produtos_pedidos1_idx` ON `carrinho_compras`.`pedido_produtos` (`pedido_id` ASC);


-- -----------------------------------------------------
-- Table `carrinho_compras`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carrinho_compras`.`categorias` ;

CREATE TABLE IF NOT EXISTS `carrinho_compras`.`categorias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(255) NULL,
  `descricao` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carrinho_compras`.`categorias_has_produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carrinho_compras`.`categorias_has_produtos` ;

CREATE TABLE IF NOT EXISTS `carrinho_compras`.`categorias_has_produtos` (
  `categorias_id` INT(11) NOT NULL,
  `produtos_id` INT(11) NOT NULL,
  PRIMARY KEY (`categorias_id`, `produtos_id`))
ENGINE = InnoDB;

CREATE INDEX `fk_categorias_has_produtos_produtos1_idx` ON `carrinho_compras`.`categorias_has_produtos` (`produtos_id` ASC);

CREATE INDEX `fk_categorias_has_produtos_categorias1_idx` ON `carrinho_compras`.`categorias_has_produtos` (`categorias_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
